services:
  app:
    build: 
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-files:/vol/web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=devpasslol
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:14-alpine
    volumes: 
      - dev-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpasslol
    healthcheck:
      test: "pg_isready --username=devuser --dbname=devdb && psql --username=devuser --dbname=devdb --list"
      timeout: 10s
      retries: 20

  

volumes:
  dev-db:
  dev-static-files: